install:
  - nuget restore

configuration:
  - Release

build:
  project: Peaky.sln
  publish_nuget: true

image: Visual Studio 2017

test:
  assemblies:
    - '**\*Tests.dll'

artifacts:
  - path: '*.nupkg'

